screen=SIMPLYSPLASH

# Main toggle (defaulted to off)
option.MOTION_BLUR=false

# Strength setting (defaulted to 0.50)
option.MOTION_BLUR_STRENGTH=0.50

# Force Iris to render as a slider
sliders=MOTION_BLUR_STRENGTH


# Menu layout
screen=MOTION_BLUR MOTION_BLUR_STRENGTH